/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type ContentStatus = 'empty' | 'generated' | 'reviewed' | 'warning';
export type ToneOfVoice = 'Sales-driven' | 'Informational' | 'Community-centric' | 'Luxury/Aspirational';
export type CopywritingFramework = 'PAS' | 'AIDA' | 'BAB' | '4Ps' | 'Storytelling' | 'Direct-Response';

export interface HookVariation {
  id: string;
  type: string;
  hookText: string;
  angle: string;
}

export interface CarouselSlide {
  slideNumber: number;
  title: string;
  body: string;
  visualCue: string;
}

export interface AdvancedSocialContent {
  frameworkUsed: CopywritingFramework;
  primaryPost: string;
  hooksAB: HookVariation[];
  carouselSlides: CarouselSlide[];
  videoScript: {
    hook0to3s: string;
    body3to15s: string;
    cta15to20s: string;
    onScreenText: string;
  };
  hashtagClusters: {
    niche: string[];
    industry: string[];
    trending: string[];
  };
  ctaVariations: {
    directMessage: string;
    saveBookmark: string;
    commentDebate: string;
    linkInBio: string;
  };
}

export interface PlatformPostData {
  text: string;
  hashtags: string;
  charCount: number;
}

export interface PlatformPosts {
  instagram: PlatformPostData;
  linkedin: PlatformPostData;
  facebook: PlatformPostData;
  youtube: PlatformPostData;
}

export interface SentimentAnalysis {
  intensity: 'Low' | 'Medium' | 'High';
  score: number; // 0 to 100 representing emotional / engagement strength
  label: string; // e.g., "Highly Sales-driven", "Informational/Technical", "Community-centric & Engaging"
  primaryEmotion: string; // e.g., "Uplifting", "Direct", "Authoritative", "Urgent"
}

export interface DayData {
  day: number;
  date: string;
  platforms?: PlatformPosts;
  imagePrompt?: string;
  status: ContentStatus;
  accuracyWarnings: string[];
  publishingTimes?: {
    instagram: string;
    linkedin: string;
    facebook: string;
    youtube: string;
  };
  toneOfVoice?: ToneOfVoice;
  complianceChecks?: {
    hasAstmWarning: boolean;
    includesFobTerms: boolean;
    disclosesOrigin: boolean;
    bilingualDoubleReview: boolean;
    noUnverifiedClaims: boolean;
  };
  sentimentAnalysis?: SentimentAnalysis;
}

export interface MonthData {
  monthIndex: number;
  themeEN: string;
  themeES: string;
  niche: string;
  isAutoGenerated: boolean;
  isComplete: boolean;
  days: DayData[];
}

export interface MarketPulseData {
  trendingTopic: string;
  architectsSearch: string;
  miamiInsight: string;
}

export interface ApiKeysConfig {
  openai: string;
  perplexity: string;
  googleTrends: string;
  gemini?: string;
}

export interface CompanyTrainingConfig {
  companyName: string;
  valueProposition: string;
  toneGuide: string;
  targetAudience: string;
  customGuidelines: string;
}

export interface GoogleAnalyticsConfig {
  measurementId: string;
  isConnected: boolean;
  simulatedViews: number;
  simulatedCTR: number;
  simulatedConversions: number;
}
